import type { Metadata } from "next";
import Header from "@/layout/header";
import Footer from "@/layout/footer";
import Aside from "@/layout/aside";

import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  subsets: ["latin"],
  display: "swap",
});

const geistMono = Geist_Mono({
  subsets: ["latin"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en">
      <body className={`${geistSans.className} ${geistMono.className} antialiased`}>
        <Header />
        <div className="flex min-h-screen">
          <Aside />
          <main className="flex-1 p-8">{children}</main>
        </div>
        <Footer />
      </body>
    </html>
  );
}